listener {
    timeout = 600 # 10 min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 1800 # 30 min
    on-timeout = systemctl suspend
}
